import Head from "next/head";
import { Container } from "@chakra-ui/react";

import ListPosts from "./components/ListPosts";
import AddPost from "./components/AddPost";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="7xl">
          <AddPost />
          <ListPosts />
        </Container>
      </main>
    </>
  );
}
